Addresses following RuntimeError for Pytorch 2.1.0+cu118 when accessing rewards with argument `numpyize=True` --------------------------------------------------------------------------- RuntimeError                              Traceback (most recent call last) <ipython-input-9-878dbfe8120c> in <cell line: 1>() ----> 1 gw.S.rewards(numpyize=True, key=reward_key)
1 frames
/usr/local/lib/python3.10/dist-packages/navigation_mdp/state.py in rewards(self, numpyize, gridded, key)
    160             rewards = [self.state_lst[idx].get_reward(key=key) for idx in range(self.n_states)]
    161             if numpyize:
--> 162                 return np.asarray(rewards, dtype=np.float32)
    163             else:
    164                 return rewards

/usr/local/lib/python3.10/dist-packages/torch/_tensor.py in __array__(self, dtype)
   1030             return self.numpy()
   1031         else:
-> 1032             return self.numpy().astype(dtype, copy=False)
   1033
   1034     # Wrap Numpy array again in a suitable tensor when done, to support e.g.

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.